name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Setup virtualenv
      run: |
        virtualenv -p /usr/bin/python ENV
        source ENV/bin/activate
        pip install -r requirements.txt
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test build
      run: |
        cd src
        python elementar.py
